export  const userData:any = [
    {
        email:"sujiths@gmail.com",
        password:"1111"
    }
]

export const users = [
    {
        avatarSrc: "/placeholder-user1.jpg",
        name: "Muhammed Anshif P",
        role: "IT, Intern",
        phone: "7736663540",
        email: "anshifm857@gmail.com",
    },
    {
        avatarSrc: "/placeholder-user2.jpg",
        name: "John Doe",
        role: "Software Engineer",
        phone: "1234567890",
        email: "john.doe@example.com",
    },
    {
        avatarSrc: "/placeholder-user3.jpg",
        name: "Jane Smith",
        role: "Product Manager",
        phone: "0987654321",
        email: "jane.smith@example.com",
    },
    {
        avatarSrc: "/placeholder-user4.jpg",
        name: "Emily Davis",
        role: "UX Designer",
        phone: "5555555555",
        email: "emily.davis@example.com",
    },
    {
        avatarSrc: "/placeholder-user5.jpg",
        name: "Michael Johnson",
        role: "Data Scientist",
        phone: "6666666666",
        email: "michael.johnson@example.com",
    },
    {
        avatarSrc: "/placeholder-user6.jpg",
        name: "Sarah Brown",
        role: "Marketing Specialist",
        phone: "7777777777",
        email: "sarah.brown@example.com",
    },
    {
        avatarSrc: "/placeholder-user7.jpg",
        name: "David Wilson",
        role: "DevOps Engineer",
        phone: "8888888888",
        email: "david.wilson@example.com",
    },
    {
        avatarSrc: "/placeholder-user8.jpg",
        name: "Laura Martinez",
        role: "Sales Manager",
        phone: "9999999999",
        email: "laura.martinez@example.com",
    },
    {
        avatarSrc: "/placeholder-user9.jpg",
        name: "James Lee",
        role: "Business Analyst",
        phone: "1010101010",
        email: "james.lee@example.com",
    },
    {
        avatarSrc: "/placeholder-user10.jpg",
        name: "Olivia Anderson",
        role: "Graphic Designer",
        phone: "2020202020",
        email: "olivia.anderson@example.com",
    }
];


export const jobList = [
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "HR Generalist",
      "description": "Handle HR operations, recruitment, talent management, and employee engagement.",
      "Activities": "Recruitment, talent management, employee relations, benefits administration.",
      "skills": "• Recruitment tools (basic)\n• HR software (basic)\n• Communication (intermediate)\n• Problem-solving (intermediate)",
      "softSkills": "• Teamwork (intermediate)\n• Adaptability (basic)\n• Empathy (basic)",
      "coreValues": "• Integrity\n• Professionalism",
      "personality": "• Detail-oriented\n• Organized",
      "eQ": "EQ: Average\nIQ: Average",
      "iQ": "₹40,000 - ₹60,000",
      "salaryRange": "Moderate",
      "_id": 1,
      "image": "/Invstbanking.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "Talent Acquisition Specialist",
      "description": "Source, attract, and hire top talent.",
      "Activities": "Sourcing, screening, interviewing, offer extension.",
      "skills": "• ATS tools (intermediate)\n• Sourcing techniques (intermediate)\n• Interviewing skills (intermediate)\n• Negotiation (basic)",
      "softSkills": "• Persuasion (intermediate)\n• Time management (intermediate)",
      "coreValues": "• Results-driven\n• Innovative",
      "personality": "• Proactive\n• Strategic",
      "eQ": "EQ: Average\nIQ: High",
      "iQ": "₹50,000 - ₹70,000",
      "salaryRange": "High",
      "_id": 2,
      "image": "/Finanalyst.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "Compensation and Benefits Manager",
      "description": "Design and implement compensation and benefits programs.",
      "Activities": "Market research, policy development, budgeting.",
      "skills": "• Compensation software (intermediate)\n• Benefits administration (intermediate)\n• Financial analysis (basic)\n• Communication (intermediate)",
      "softSkills": "• Analytical thinking (intermediate)\n• Strategic thinking (basic)",
      "coreValues": "• Fairness\n• Transparency",
      "personality": "• Detail-oriented\n• Analytical",
      "eQ": "EQ: Average\nIQ: High",
      "iQ": "₹60,000 - ₹80,000",
      "salaryRange": "Moderate",
      "_id": 3,
      "image": "/managementconsult.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "Learning and Development Specialist",
      "description": "Design and deliver training programs.",
      "Activities": "Needs assessment, content creation, facilitation.",
      "skills": "• Instructional design (intermediate)\n• Training delivery (intermediate)\n• Adult learning theory (basic)\n• Technology-based learning (basic)",
      "softSkills": "• Creativity (intermediate)\n• Storytelling (basic)",
      "coreValues": "• Continuous learning\n• Collaboration",
      "personality": "• Innovative\n• Engaging",
      "eQ": "EQ: High\nIQ: Average",
      "iQ": "₹50,000 - ₹70,000",
      "salaryRange": "High",
      "_id": 4,
      "image": "/corporatefinn.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "HRIS Analyst",
      "description": "Implement and maintain HR systems and data analysis.",
      "Activities": "System administration, data analysis, reporting.",
      "skills": "• HRIS software (intermediate)\n• Data analysis (intermediate)\n• Reporting tools (basic)\n• Technical skills (intermediate)",
      "softSkills": "• Attention to detail (intermediate)\n• Technical expertise (intermediate)",
      "coreValues": "• Accuracy\n• Technical expertise",
      "personality": "• Detail-oriented\n• Analytical",
      "eQ": "EQ: Average\nIQ: High",
      "iQ": "₹40,000 - ₹60,000",
      "salaryRange": "Moderate",
      "_id": 5,
      "image": "/Riskmamag.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "Employee Engagement Specialist",
      "description": "Develop and implement employee engagement initiatives.",
      "Activities": "Survey design, program development, communication.",
      "skills": "• Survey tools (basic)\n• Communication (intermediate)\n• Program management (intermediate)\n• Creativity (basic)",
      "softSkills": "• Empathy (intermediate)\n• Influencing (basic)",
      "coreValues": "• Empathy\n• Creativity",
      "personality": "• Innovative\n• Engaging",
      "eQ": "EQ: High\nIQ: Average",
      "iQ": "₹40,000 - ₹60,000",
      "salaryRange": "High",
      "_id": 6,
      "image": "/Businessdevelopment.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "Labor Law Compliance Specialist",
      "description": "Ensure compliance with labor laws and regulations.",
      "Activities": "Research, policy development, training.",
      "skills": "• Labor laws (intermediate)\n• Compliance software (basic)\n• Policy development (intermediate)\n• Training delivery (basic)",
      "softSkills": "• Analytical thinking (intermediate)\n• Attention to detail (intermediate)",
      "coreValues": "• Compliance\n• Integrity",
      "personality": "• Detail-oriented\n• Analytical",
      "eQ": "EQ: Average\nIQ: High",
      "iQ": "₹50,000 - ₹70,000",
      "salaryRange": "Moderate",
      "_id": 7,
      "image": "/corporatefinn.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "HR",
      "jobTitle": "Performance Management Specialist",
      "description": "Design and implement performance management systems.",
      "Activities": "Policy development, training, data analysis.",
      "skills": "• Performance management software (intermediate)\n• Policy development (intermediate)\n• Data analysis (intermediate)\n• Communication (intermediate)",
      "softSkills": "• Strategic thinking (intermediate)\n• Influencing",
      "coreValues": "",
      "personality": "",
      "eQ": "",
      "iQ": "",
      "salaryRange": "",
      "_id": 8,
      "image": "/TAxconsultant.jpeg"
    },
    {
      "type": "management",
      "fieldOfStudy": "Marketing",
      "jobTitle": "Marketing Executive",
      "description": "Develop and execute marketing strategies.",
      "Activities": "Campaign development, market research, brand management.",
      "skills": "• Marketing software (basic)\n• Data analysis (basic)\n• Creative thinking (intermediate)\n• Communication (intermediate)",
      "softSkills": "• Adaptability (intermediate)\n• Time management (intermediate)",
      "coreValues": "• Innovation\n• Creativity",
      "personality": "• Strategic\n• Innovative",
      "eQ": "EQ: Average\nIQ: High",
      "iQ": "₹35,000 - ₹50,000",
      "salaryRange": "High",
      "_id": 9,
      "image": "/Invstbanking.jpeg"
    }]